# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuODK
                                 A QGIS plugin
 A link between ODK Central data and QGIS
 Originally Generated by Plugin Builder, updated with 'help' from Claude
                             -------------------
        begin                : 2024-03-30
        copyright            : (C) 2024-2026 by Walking-the-Talk
        email                : chris.york@walking-the-talk.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QuODK class from file QuODK.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """

    # Check dependencies before loading plugin
    from .dependency_checker import check_dependencies

    missing_packages = check_dependencies()

    if missing_packages:
        # Show dependency installation dialog
        from .dependency_dialog import show_dependency_dialog

        if not show_dependency_dialog(missing_packages, iface):
            # User cancelled or installation requires restart
            from qgis.PyQt.QtWidgets import QMessageBox
            QMessageBox.critical(
                iface.mainWindow(),
                "QuODK - Cannot Load",
                "QuODK cannot load without required dependencies.\n\n"
                "Please install the missing packages and restart QGIS."
            )

            # Return a dummy object with required methods to prevent QGIS errors
            class QuODK_MissingDeps:
                def __init__(self, iface):
                    pass
                def initGui(self):
                    pass
                def unload(self):
                    pass
            return QuODK_MissingDeps(iface)

    # All dependencies present, load plugin normally
    from .quodk import QuODK
    return QuODK(iface)
