# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuODK
                                 A QGIS plugin
 A link between ODK Central data and QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-30
        git sha              : $Format:%H$
        copyright            : (C) 2024-2026 by Walking-the-Talk
        email                : chris.york@walking-the-talk.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import json
import os
import uuid
from datetime import  datetime, time, timedelta
from math import isnan
from pathlib import Path
#import requests
from qgis.PyQt.QtCore import QSettings, QMetaType, Qt
from qgis.PyQt.QtGui import QFont, QPixmap
from qgis.PyQt.QtWidgets import QComboBox, QFileDialog, QTableWidgetItem
from qgis.core import QgsExpressionContextUtils, QgsProject
import pandas as pd

# Import the QuODK library (backend logic)
from . import quodk_lib
from .scramble import manage_credentials

class auto_pilot_interface:

    def __init__(self, iface, dialog, plugin_dir):
        """
        Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        :param dialog: The QuODK UI dialog
        :param plugin_dir: Plugin directory path from main plugin
        """
        # Save reference to the QGIS interface
        self.iface = iface
        self.dlg = dialog
        self.plugin_dir = plugin_dir
        # Declare instance attributes
        self.session_token = ''
        self.data_grabber = None  # Will be initialized after authentication
        # Default values
        self.odkURL = ''
        self.odkUser = ''
        self.odkPass = ''
        self.pid = 0
        self.xmlFormId = ''
        self.FormName = ''
        self.projection = 'EPSG:4326'
        self.headFont = QFont()
        self.LayerName = ''
        self.auto_entitystatus = ["New", "Updated"]
        self.df_submissions = pd.DataFrame()
        # Initialize credential manager
        self.credential_manager = manage_credentials()
        # Auto pilot file path - load from settings or use default
        self.auto_pilot_path = self.load_auto_pilot_path()
        self.auto_pilot_config = []
        # Set the dates
        self.DateEnd = (quodk_lib.timeaware(datetime.combine(datetime.now(), time.min)) + timedelta(hours=23, minutes=59, seconds=59.99))
        self.DateStart = quodk_lib.timeaware(datetime.combine(datetime.now(), time.min))
        if hasattr(self.dlg, 'DateEnd'):
            self.dlg.DateEnd.setDate(self.DateEnd)
            self.dlg.DateEnd.setEnabled(False)
        if hasattr(self.dlg, 'DateStart'):
            self.dlg.DateStart.setDate(self.DateStart)
            self.dlg.DateStart.setEnabled(False)
        if hasattr(self.dlg, 'attributeFilter'):
            self.dlg.attributeFilter.addItem('-Select Attribute-')

    def auto_pilot_msg (self, text, style="color: black; background: none", msg_type='both'):
        if msg_type == 'msg_auto_pilot' and hasattr(self.dlg, 'msg_auto_pilot'):
            self.dlg.msg_auto_pilot.setText(text)
            self.dlg.msg_auto_pilot.setStyleSheet(style)

    # ====================================================================================================
    # Auto Pilot settings and Credentials
    # ====================================================================================================

    def load_auto_pilot_path(self):
        """
        Load the saved Auto Pilot file path from QGIS settings.
        Returns the saved path or default path in home directory.
        """
        settings = QSettings()
        saved_path = settings.value('QuODK/auto_pilot_path', '')
        if saved_path and os.path.isfile(saved_path):
            return saved_path
        else:
            # Return default path
            return os.path.join(Path.home(), 'quodk.json')

    def save_auto_pilot_path(self, file_path):
        """
        Save the most recent Auto Pilot file path to QGIS settings.
        Args:
            file_path: Full path to the JSON file
        """
        settings = QSettings()
        settings.setValue('QuODK/auto_pilot_path', file_path)
        self.auto_pilot_path = file_path

    def select_auto_pilot_file(self):
        """
        Open a file dialog to allow user to select an Auto Pilot JSON file.
        Supports both encrypted and plain-text JSON files.
        Updates the stored path and reloads Auto Pilot settings.
        """
        self.auto_pilot_config = None
        file_path, _ = QFileDialog.getOpenFileName(
            None,
            "Select QuODK Auto Pilot settings File",
            self.auto_pilot_path,
            "JSON Files (*.json);;All Files (*)"
        )
        if file_path:
            try:
                with open(file_path, 'r') as fp:
                    config = json.load(fp)
                self.auto_pilot_msg("Loaded JSON Auto Pilot file...",
                             "background: green", 'msg_auto_pilot')
            except json.JSONDecodeError:
                self.auto_pilot_msg("Error: Selected file is not valid JSON or encrypted config",
                            "background: red", 'msg_auto_pilot')
                return
            except Exception as e:
                self.auto_pilot_msg(f"Error reading file: {str(e)}",
                            "background: red", 'msg_auto_pilot')
                return
            # Validate and load Auto Pilot settings
            if config:
                self.clearFilter_auto()
                self.dlg.dataTable_auto.clear()
                self.dlg.dataTable_auto.setRowCount(0)
                self.dlg.dataTable_auto.setColumnCount(0)
                self.save_auto_pilot_path(file_path)
                if config['lastEndDateTime']:
                    self.dlg.sinceLastDownload.setVisible(True)
                else:
                    self.dlg.sinceLastDownload.setVisible(False)
                    self.dlg.sinceLastDownload.setChecked(False)
                if config['permissions'] == 'locked':
                    if hasattr(self.dlg, 'quodkey_auto'):
                        self.auto_pilot_msg(f"LOCKED Auto Pilot loaded from:\n{file_path}\nPlease unlock with the key you were given",
                                            "background: orange", 'msg_auto_pilot')
                        self.dlg.quodkey_auto.setVisible(True)
                        self.dlg.unlock_quodkey.setVisible(True)
                        self.dlg.label_quodkey.setVisible(True)
                        self.auto_pilot_config = config
                        if hasattr(self.dlg, 'DateStart'):
                            self.dlg.DateStart.setEnabled(False)
                        if hasattr(self.dlg, 'DateEnd'):
                            self.dlg.DateEnd.setEnabled(False)
                else:
                    self.dlg.btnSelectConfig.setStyleSheet("background: DarkSeaGreen")
                    if hasattr(self.dlg, 'DateStart'):
                        self.dlg.DateStart.setEnabled(True)
                    if hasattr(self.dlg, 'DateEnd'):
                        self.dlg.DateEnd.setEnabled(True)
                    self.load_auto_pilot(config)

    def unlock_quodkey(self):

        locked = [self.auto_pilot_config['odkPass'],self.auto_pilot_config['odkUser']]
        unlocked = self.credential_manager.unlock_permissions(locked[0],locked[1],self.dlg.quodkey_auto.text())
        if unlocked[2] == 'Unlocked':
            self.auto_pilot_config['odkPass'] = unlocked[0]
            self.auto_pilot_config['odkUser'] = unlocked[1]
            self.auto_pilot_config['permissions'] = 'unlocked'
            self.auto_pilot_config['trigger'] = 'auto'
            if hasattr(self.dlg, 'DateStart'):
                self.dlg.DateStart.setEnabled(True)
            if hasattr(self.dlg, 'DateEnd'):
                self.dlg.DateEnd.setEnabled(True)
            self.update_auto_pilot_file(self.auto_pilot_config,self.auto_pilot_path,'unlocking')
            self.dlg.quodkey_auto.setVisible(False)
            self.dlg.unlock_quodkey.setVisible(False)
            self.dlg.label_quodkey.setText('Successfully unlocked')
            self.load_auto_pilot(self.auto_pilot_config)
        else:
            self.auto_pilot_msg(f"'Unable to unlock Quodkey: {unlocked['feedback']}", "background: red", 'msg_auto_pilot')

    def load_auto_pilot(self, config):

        # Check if it has required keys
        required_keys = ['odkURL', 'odkUser', 'odkPass', 'pid', 'xmlFormId']
        if all(key in config for key in required_keys):
            if not self.auto_pilot_config:
                self.auto_pilot_config = config
            self.auto_pilot_msg(f"Auto Pilot loaded",
                        "background: lightgreen", 'msg_auto_pilot')
            self.odkURL = config['odkURL']
            unscrambled, unscrambleduser, feedback = self.credential_manager.unscramble(config['odkPass'], config['odkUser'], config['trigger'])
            if feedback == 'Unlocked':
                self.odkPass = unscrambled
                self.odkUser = unscrambleduser
            else:
                self.auto_pilot_msg(f"Auto Pilot failed to load:\n\n{feedback}",
                        "background: lightcoral", 'msg_auto_pilot')
                return
            trigger = config['trigger']
            self.selected_projectID = config['pid']
            self.xmlFormId = config['xmlFormId']
            self.FormName = config['FormName']
            self.projection = config['crs']
            # Load auto-pilot filter settings
            self.attributeFilter = config['attributeFilter']
            self.valueFilter = config['valueFilter']
            self.filterExclude = config['filterExclude']
            self.EntityList = config['entitylist']
            self.EnityFilter = config['entityFilter']
            self.EnityFilterValue = config['entityFilterValue']
            self.EntityFilterExclude = config['entityFilterExclude']
            self.repeats = config['repeats']
            self.permissions = config['permissions']
            self.lastEnd = config['lastEndDateTime']
            if hasattr(self.dlg, 'label_last_end_time') and self.lastEnd:
                self.dlg.label_last_end_time.setText(self.lastEnd)
            else:
                self.dlg.label_last_end_time.setText('')
            if len(config['repeats']) > 1:
                rptmsg = 'with repeat groups: '
                for rpt in config['repeats']:
                    if rpt['repeatGroup'] =='Main' or rpt['repeatGroup'] ==self.EntityList:
                        pass
                    else:
                        rptmsg += f"{rpt['repeatGroup']}, "
            else:
                rptmsg = ''
            update_msg = (f"Auto-pilot loaded from:\n{self.auto_pilot_path}\n"
                        f"Server: {self.odkURL}\n"
                        f"Form name: {self.FormName} {rptmsg}\n")
            if self.EntityList:
                update_msg += f"Associated Entity list: {self.EntityList}"
            self.auto_pilot_msg(update_msg, "color: black; background: none", 'msg_auto_pilot')
            #self.dlg.start_auto_pilot.setEnabled(True)
        else:
            self.auto_pilot_msg("Invalid Auto-pilot file. Missing required fields",
                        "background: orange", 'msg_auto_pilot')

    def update_auto_pilot_file(self, config, file_path, trigger):
            # Encrypt and save Auto Pilot using credential manager
        try:
            if trigger == 'auto':
                scrambled = self.credential_manager.scrambler(self.odkPass,self.odkUser,trigger)
                config['odkPass'] = scrambled[0]
                config['odkUser'] = scrambled[1]
            if trigger == 'config':
                config['odkPass'] = self.quodkey_pass
            with open(file_path, 'w') as fp:
                json.dump(config, fp)
            self.save_auto_pilot_path(file_path)
            self.auto_pilot_msg(f"Encrypted Auto Pilot file updated and saved to:\n{file_path}",
                            "background: lightgreen", 'msg_auto_pilot')
        except Exception as e:
            self.auto_pilot_msg(f"Error saving file: {str(e)}",
                        "background: red", 'msg_auto_pilot')
            print(f"unable to save file {e}")

    def auto_pilot(self):
        self.auto_pilot_msg("", "background: none", 'msg_auto_pilot')
        self.keyID = []
        self.odk_geometry = []
        self.repeatGroups = []
        repeatgroup = ''
        if not self.session_token:
            session_manager = quodk_lib.SessionToken(self.odkURL, self.odkUser, self.odkPass)
            self.session_token = session_manager.get_token()
            if not self.session_token:
                self.auto_pilot_msg("Unable to connect to ODK server", "background: red", 'msg_auto_pilot')
                return
        self.data_grabber = quodk_lib.CentralDataGrab(self.session_token, self.odkURL)
        for i in self.repeats:
            repeatgroup = i['repeatGroup']
            self.repeatGeom = i['geom']
            start_enabled = self.dlg.start_auto_pilot.isEnabled() if hasattr(self.dlg, 'start_auto_pilot') else False
            if repeatgroup == self.EntityList and self.EntityList !='Exclude Entities':
                self.keyLevel = "ENTITY_KEY"
                for status in self.auto_entitystatus:  # check new and updated entities within date range
                    self.LayerName = f'QuODK_ENTITY_{self.EntityList}_{status}'
                    self.df_entities, geom_opts, response, response_message = self.data_grabber.get_entities(project_id=self.selected_projectID,
                                                                      entity_list_name=self.EntityList,
                                                                      date_start=self.strSdate,
                                                                      date_end=self.strEdate,
                                                                      status=status)
                    if self.df_entities.shape[0] > 0:
                        if self.EnityFilterValue and self.EnityFilter:
                            if self.EntityFilterExclude == "True":
                                self.df_entities = self.df_entities[
                                    self.df_entities[self.EnityFilter] != self.EnityFilterValue]
                            else:
                                self.df_entities = self.df_entities[
                                    self.df_entities[self.EnityFilter] == self.EnityFilterValue]

                        nogeom, count = quodk_lib.load_layer_to_canvas(self.df_entities, self.LayerName,
                                                                            self.keyLevel, self.repeatGeom,
                                                                            self.projection)
                        self.updateMsg += f"{count} {status} entities loaded\n"
            else:
                if repeatgroup == "Main":
                    self.keyLevel = "KEY"
                    self.LayerName = f'QuODK_{self.FormName}'
                else:
                    self.keyLevel = "PARENT_KEY"
                    self.LayerName = f'QuODK_{self.FormName}_{repeatgroup}'
                df_odk, geom_opts, response, response_message = self.data_grabber.get_submissions(project_id=self.selected_projectID,
                                                                                   xml_form_id=self.xmlFormId,
                                                                                   repeat_group=repeatgroup,
                                                                                   date_start=self.strSdate,
                                                                                   date_end=self.strEdate)
                if response == 200:
                    if self.keyLevel == "KEY":
                        self.lastEnd = str(datetime.now())
                        if self.valueFilter and self.attributeFilter:
                            if self.filterExclude == "True":
                                df_odk = df_odk[
                                    df_odk[self.attributeFilter] != self.valueFilter]
                            else:
                                df_odk = df_odk[
                                    df_odk[self.attributeFilter] == self.valueFilter]
                    try:
                        self.AttachmentsTotal = df_odk['__system.attachmentsPresent'].sum()
                    except Exception:
                        self.AttachmentsTotal = 0

                    if df_odk.shape[0] > 0:
                        start_enabled = self.dlg.start_auto_pilot.isEnabled() if hasattr(self.dlg, 'start_auto_pilot') else True
                        # after setting / resetting the date, check how many submissions (KEY)
                        if self.keyLevel == "KEY" and (not start_enabled):
                            self.df_submissions = df_odk
                            if self.df_submissions.shape[0] > 0 and hasattr(self.dlg, 'start_auto_pilot'):
                                headers = list(self.df_submissions)
                                for header in headers:
                                    self.dlg.attributeFilter.addItem(header)
                                self.dlg.attributeFilter.setEnabled(True)
                                self.dlg.filterExclude.setEnabled(True)
                                self.dlg.filterExclude.setCheckable(True)
                                self.changeFilterState_auto()
                                self.dlg.start_auto_pilot.setEnabled(True)
                                self.dlg.Attachments_auto.setEnabled(True)
                                self.filterID = list(self.df_submissions['KEY'])
                                self.updateMsg = f"{self.df_submissions.shape[0]} submissions found and {self.AttachmentsTotal} attachments"
                            else:
                                self.updateMsg = "There are no submissions in this date range"
                                self.dlg.Attachments_auto.setEnabled(False)
                            self.update_auto_table(self.df_submissions)
                            self.auto_pilot_msg(str(self.updateMsg), '', 'msg_auto_pilot')
                            self.updateMsg = ''
                            return
                        df_odk= df_odk[df_odk[self.keyLevel].isin(self.filterID)]
                        nogeom, count = quodk_lib.load_layer_to_canvas(df_layer=df_odk,
                                                                       LayerName=self.LayerName,
                                                                       keyLevel=self.keyLevel,
                                                                       geomType=self.repeatGeom,
                                                                       projection=self.projection)
                        self.updateMsg += f"\n{self.LayerName}\nLayer added projected using {self.projection}\n({count} features and {nogeom} rows without geometry)\n"
                    else:
                        if self.keyLevel == "KEY":
                            df_latest, geom_opts, response, response_message = self.data_grabber.get_submissions(
                                project_id=self.selected_projectID,
                                xml_form_id=self.xmlFormId,
                                repeat_group=repeatgroup,
                                top_n=1)
                            latest_record = df_latest.iloc[0]['__system.submissionDate']
                            self.auto_pilot_msg(f"No submissions found between {self.DateStart} and {self.DateEnd}\n"
                                                f"The latest submission was {latest_record}", "background: orange", 'msg_auto_pilot')
                            return
                        else:
                            self.updateMsg += f"No submissions from {repeatgroup} found\n"
                else:
                    self.auto_pilot_msg(f"{response_message['message']} Please give the following number to the person that provided you with the Auto Pilot file: {response_message['code']}",
                                        "background: red", 'msg_auto_pilot')
                    return
        self.auto_pilot_config['lastEndDateTime'] = self.lastEnd
        self.update_auto_pilot_file(self.auto_pilot_config, self.auto_pilot_path, 'auto')
        self.auto_pilot_msg(str(self.updateMsg), '', 'msg_auto_pilot')

    def onAutoPilotDateChanged(self):
        """Handle date range changes, converting to UTC for API."""
        if hasattr(self.dlg, 'sinceLastDownload'):
            if self.dlg.sinceLastDownload.isChecked():
                datetime_str = datetime.fromisoformat(self.lastEnd)
                sDate = quodk_lib.timeaware(datetime_str)
                if hasattr(self.dlg, 'DateStart'):
                    self.dlg.DateStart.setEnabled(False)
                    self.DateStart = sDate
            else:
                self.dlg.DateStart.setEnabled(True)
                self.DateStart = quodk_lib.timeaware(self.dlg.DateStart.dateTime())
        if hasattr(self.dlg, 'DateEnd'):
            self.DateEnd = self.dlg.DateEnd.date()
            self.DateEnd = (quodk_lib.timeaware(self.dlg.DateEnd.dateTime()) +
                            timedelta(hours=23, minutes=59, seconds=59.99))

        if self.DateStart > self.DateEnd:
            self.auto_pilot_msg(self.tr_date_error, "color: black; background: none", 'both')
            return
        else:
            # Convert to API-readable string format
            self.strSdate = str(self.DateStart).replace(" ", "T") + "Z"
            self.strEdate = str(self.DateEnd).replace(" ", "T") + "Z"

        if self.auto_pilot_config:
            self.dlg.start_auto_pilot.setEnabled(False)
            self.auto_pilot()
        else:
            return

    def update_auto_table(self, df_table):
        self.table = self.dlg.dataTable_auto
        headings = list(df_table)
        if self.dlg.valueFilter.currentText():
            if self.filterExclude is True:
                df_table = df_table[df_table[self.dlg.attributeFilter.currentText()] != self.dlg.valueFilter.currentText()]
            else:
                df_table = df_table[df_table[self.dlg.attributeFilter.currentText()] == self.dlg.valueFilter.currentText()]
            self.auto_pilot_msg(f"{df_table.shape[0]} filtered submissions found", '', 'msg_auto_pilot')
        self.filterID = list(df_table['KEY'])
        self.attachmentfilter = self.filterID
        self.table.setRowCount(df_table.shape[0])
        self.table.setColumnCount(df_table.shape[1])
        self.table.setHorizontalHeaderLabels(headings)
        #check for underscores in headings and highlight in bold
        i = 0
        self.headFont.setBold(True)
        for heading in headings:
            if '_' in heading and '__' not in heading and 'base_version' not in heading:
                self.table.horizontalHeaderItem(i).setFont(self.headFont)
            i += 1
        self.table.resizeColumnsToContents()
        # Populate table
        df_array = df_table.values
        for row in range(df_table.shape[0]):
            for col in range(df_table.shape[1]):
                self.table.setItem(
                    row, col, QTableWidgetItem(str(df_array[row, col])))

    def filter_items_auto(self):
        self.dlg.valueFilter.setEnabled(True)
        self.dlg.valueFilter.clear()
        self.dlg.valueFilter.addItem('-Select Value-')
        if self.dlg.attributeFilter.currentText() != '-Select Attribute-':
            uniqueValues = self.df_submissions[self.dlg.attributeFilter.currentText()].unique().tolist()
            for u in uniqueValues:
                if u is not None:
                    self.dlg.valueFilter.addItem(str(u))

    def filter_value_auto(self):
        """Handle filter value selection from filter dropdown."""
        self.dlg.clearFilter.setEnabled(True)
        self.valueFilter = self.dlg.valueFilter.currentText()
        self.update_auto_table(self.df_submissions)

    def changeFilterState_auto(self):
        """Toggle filter state between Include and Exclude """
        if self.dlg.filterExclude.isChecked():
            self.dlg.filterExclude.setText("not")
            self.filterExclude =  True
        else:
            self.dlg.filterExclude.setText("is")
            self.filterExclude =  False

    def clearFilter_auto(self):
        """Clear autopilot filters and reset table."""
        self.dlg.clearFilter.setEnabled(False)
        self.dlg.attributeFilter.setCurrentIndex(0)
        self.dlg.valueFilter.clear()
        self.attributeFilter = None
        self.valueFilter = None
        self.filterExclude = False
        if self.df_submissions.shape[0] >0:
            self.update_auto_table(self.df_submissions)

    def updateFilterID(self, df_table):
        updateMsg = ''
        if self.keyLevel == "KEY":
            self.filterID = list(df_table['KEY'])
            self.attachmentfilter = self.filterID
            if len(self.repeatGroups) >1 :
                list_of_repeats = [rg.replace('Submission.','') for rg in self.repeatGroups[:1]]
                rg_msg = (f"Repeat groups: {list_of_repeats}\n")
            else:
                rg_msg = ''
            self.AttachmentsTotal = df_table['__system.attachmentsPresent'].sum()
            updateMsg = (f"{self.tr_submissions_found}{df_table.shape[0]} "
                              f"({self.AttachmentsTotal} attachments)\n") + rg_msg

        elif self.keyLevel == "PARENT_KEY":
            self.filterID = list(df_table['PARENT_KEY'])
            updateMsg = (f" {self.tr_submissions_found}{df_table.shape[0]} "
                              f"in: {self.repeatGroups} (ODK_repeat)\n")

        elif self.keyLevel == "ENTITY_KEY":
            self.filterID = list(df_table['ENTITY_KEY'])
            updateMsg = f"Entities_found {df_table.shape[0]}\n"
        #updateMsg += f" {nogeom} submissions with no geometry (will not be displayed)"
        self.auto_pilot_msg(str(updateMsg), "background: none", 'submissions')

    # ====================================================================================================
    # Attachment Download
    # ====================================================================================================

    def download_images(self):
        """Download attachments for filtered submissions."""
        try:
            default_folder: str = QgsExpressionContextUtils.projectScope(QgsProject.instance()).variable(
                'ODK_image_path')
            if default_folder is None:
                default_folder = os.path.join(os.path.expanduser('~'), 'ODK_images')
        except Exception as e:
            default_folder = os.path.join(Path.home(), 'ODK_images')
            print(e)
        aFolder = QFileDialog.getExistingDirectory(None, 'Folder for images', default_folder,
                                                   QFileDialog.ShowDirsOnly | QFileDialog.DontResolveSymlinks)
        if not aFolder:
            return
        self.dlg.progressBar.setRange(0, 100)
        self.dlg.progressBar.setTextVisible(True)
        if self.dlg.attach_overwrite.isChecked():
            overwrite = True
        else:
            overwrite = False

        try:
            def progress_update(current, total):
                progress = int((current / total) * 100)
                self.dlg.progressBar.setValue(progress)

            count, missing, skipped = self.data_grabber.download_attachments(
                self.selected_projectID,
                self.xmlFormId,
                self.attachmentfilter,
                aFolder,
                self.AttachmentsTotal,
                self.odkUser,
                self.odkPass,
                overwrite,
                progress_callback=progress_update
            )
            self.auto_pilot_msg(
                f" {count} attachments downloaded to {aFolder} \n {skipped} skipped (already in local folder)\n {missing}",
                "color: black; background: DarkSeaGreen", 'msg_auto_pilot')
            # Add project variable for image path
            QgsExpressionContextUtils.setProjectVariable(
                QgsProject.instance(), 'ODK_image_path', aFolder)

        except Exception as e:
            self.set_msg(f"{self.tr_attachments_error}: {str(e)}",
                         "color: black; background: red", 'submissions')