# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuODK
                                 A QGIS plugin
 A link between ODK Central data and QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-30
        git sha              : $Format:%H$
        copyright            : (C) 2024-2026 by Walking-the-Talk
        email                : chris.york@walking-the-talk.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
from datetime import datetime

from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon, QPixmap
from qgis.PyQt.QtWidgets import QAction, QButtonGroup
from qgis.core import QgsCoordinateReferenceSystem

from .autopilot import auto_pilot_interface
# Import the dialogs
from .quodkui import QuODKui, QuODKAutoPilot
# Import the refactored UI interface
from .quodk_ui import QuodkInterface


class QuODK:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'QuODK_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&QuODK')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        self.first_start_auto_pilot = None

        # Interface instances will be created on first run
        self.interface = None
        self.interface_auto_pilot = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QuODK', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = f"{self.plugin_dir}/quodk_icon.png"
        auto_icon_path = f"{self.plugin_dir}/quodk_ap_icon.png"
        self.add_action(
            icon_path,
            text=self.tr(u'QuODK'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # Add second action for Auto-Pilot dialog
        self.add_action(
            icon_path,
            text=self.tr(u'QuODK Auto-Pilot'),
            callback=self.run_auto_pilot,
            add_to_toolbar=False,  # Only add to menu, not toolbar
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True
        self.first_start_auto_pilot = True



    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&QuODK'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start:
            self.first_start = False
            self.dlg = QuODKui()
            self.interface = QuodkInterface(self.iface, self.dlg, self.plugin_dir)

            # Create the interface instance with the dialog and plugin directory
            #self.interface = QuodkInterface(self.iface, self.dlg, self.plugin_dir)

            # Setup UI connections
            self.setup_ui_connections()

        # Reset date range to today
        if hasattr(self.dlg, 'DateStart'):
            self.dlg.DateStart.setDate(datetime.now())
        if hasattr(self.dlg, 'DateEnd'):
            self.dlg.DateEnd.setDate(datetime.now())


        # Show the dialog

        self.dlg.show()

        # Run the dialog event loop
        result = self.dlg.exec()

    def run_auto_pilot(self):
        """Run method for Auto-Pilot dialog"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start_auto_pilot:
            self.first_start_auto_pilot = False
            self.dlg_auto_pilot = QuODKAutoPilot()
            self.interface_auto_pilot = auto_pilot_interface(self.iface, self.dlg_auto_pilot, self.plugin_dir)

            # Setup UI connections for auto-pilot dialog
            self.setup_ui_connections_auto_pilot()

        # Reset date range to today
        self.dlg_auto_pilot.DateStart.setDate(datetime.now())
        self.dlg_auto_pilot.DateEnd.setDate(datetime.now())

        # Show the dialog
        self.dlg_auto_pilot.show()

        # Run the dialog event loop
        result = self.dlg_auto_pilot.exec()

    def setup_ui_connections(self):
        """Setup all UI element connections to interface methods. Where necessary use auto / manual / config for routing / options"""

        # Date controls
        if hasattr(self.dlg, 'DateStart'):
            self.dlg.DateStart.dateChanged.connect(lambda: self.interface.onDateChanged('manual'))
        if hasattr(self.dlg, 'DateEnd'):
            self.dlg.DateEnd.dateChanged.connect(lambda: self.interface.onDateChanged('manual'))
        if hasattr(self.dlg, 'load_all'):
            self.dlg.load_all.toggled.connect(self.interface.DateUpdate)
        # Connection buttons
        if hasattr(self.dlg, 'ODK_connect'):
            self.dlg.ODK_connect.clicked.connect(lambda: self.interface.connectODK('manual'))
        if hasattr(self.dlg, 'ODK_connect_go'):
            self.dlg.ODK_connect_go.clicked.connect( self.interface.auto_pilot)
        if hasattr(self.dlg, 'ODK_connect_test'):
            self.dlg.ODK_connect_test.clicked.connect(lambda: self.interface.connectODK('manual'))
        if hasattr(self.dlg, 'encrypt'):
            self.dlg.encrypt.clicked.connect(lambda: self.interface.check_credentials(True))

        # Project/Form/Repeat navigation
        if hasattr(self.dlg, 'projectID'):
            self.dlg.projectID.activated.connect(lambda: self.interface.forms_list('manual'))
        if hasattr(self.dlg, 'formID'):
            self.dlg.formID.activated.connect(lambda: self.interface.repeats_list('manual'))
        if hasattr(self.dlg, 'formID_2'):
            self.dlg.formID_2.activated.connect(lambda: self.interface.repeats_list('config'))
        if hasattr(self.dlg, 'repeatGroup'):
            self.dlg.repeatGroup.activated.connect(lambda: self.interface.list_submissions(None,'manual'))
        if hasattr(self.dlg, 'odk_geometry'):
            self.dlg.odk_geometry.activated.connect(self.interface.set_geometry)

        # Filtering (differentiate between manual or config)
        if hasattr(self.dlg, 'attributeFilter'):
            self.dlg.attributeFilter.activated.connect(lambda: self.interface.filter_items('manual'))
        if hasattr(self.dlg, 'attributeFilter_2'):
            self.dlg.attributeFilter_2.activated.connect(lambda: self.interface.filter_items('config'))
        if hasattr(self.dlg, 'valueFilter'):
            self.dlg.valueFilter.activated.connect(lambda: self.interface.filter_Value('manual'))
        if hasattr(self.dlg, 'valueFilter_2'):
            self.dlg.valueFilter_2.activated.connect(lambda: self.interface.filter_Value('config'))
        if hasattr(self.dlg, 'entityValueFilter'):
            self.dlg.entityValueFilter.activated.connect(lambda: self.interface.filter_Value('entity_config'))
        if hasattr(self.dlg, 'entityFilter'):
            self.dlg.entityFilter.activated.connect(lambda: self.interface.filter_items('entity_config'))
        if hasattr(self.dlg, 'entityFilter_2'):
            self.dlg.entityFilter_2.activated.connect(lambda: self.interface.filter_items('config'))
        if hasattr(self.dlg, 'add_manual_filter'):
            self.dlg.add_manual_filter.clicked.connect(self.interface.add_filter_value)
        if hasattr(self.dlg, 'clearFilter'):
            self.dlg.clearFilter.clicked.connect(lambda: self.interface.clearFilter('manual'))
        if hasattr(self.dlg, 'clearFilter_2'):
            self.dlg.clearFilter_2.clicked.connect(lambda: self.interface.clearFilter('config'))
        if hasattr(self.dlg, 'filterExclude'):
            self.dlg.filterExclude.clicked.connect(lambda: self.interface.changeFilterState('manual'))
        if hasattr(self.dlg, 'filterExclude_2'):
            self.dlg.filterExclude_2.clicked.connect(lambda: self.interface.changeFilterState('config'))
        if hasattr(self.dlg, 'entityFilterExclude'):
            self.dlg.entityFilterExclude.clicked.connect(lambda: self.interface.changeFilterState('entity_config'))

        # Entity list selection
        if hasattr(self.dlg, 'dataset') and hasattr(self.interface, 'select_entity_list'):
            self.dlg.dataset.activated.connect(lambda: self.interface.select_entity_list ('manual'))
        if hasattr(self.dlg, 'dataset_config') and hasattr(self.interface, 'select_entity_list'):
            self.dlg.dataset_config.activated.connect(lambda: self.interface.select_entity_list('config'))
        if hasattr(self.dlg, 'entity_status') and hasattr(self.interface, 'list_Entities'):
            self.dlg.entity_status.activated.connect(lambda: self.interface.list_Entities('manual'))

        # Auto-pilot settings file management
        if hasattr(self.dlg, 'btnSelectConfig'):
            self.dlg.btnSelectConfig.clicked.connect(self.interface.select_auto_pilot_file)
        if hasattr(self.dlg, 'btnSaveConfigAs'):
            self.dlg.btnSaveConfigAs.clicked.connect(lambda: self.interface.create_auto_pilot_file('config'))
        if hasattr(self.dlg, 'btnConfigInfo'):
            self.dlg.btnConfigInfo.clicked.connect(self.interface.show_config_file_info)
        if hasattr(self.dlg, 'copy_central_settings'):
            self.dlg.copy_central_settings.clicked.connect(self.interface.copy_central_settings)
        if hasattr(self.dlg, 'GenerateKey'):
            self.dlg.GenerateKey.clicked.connect(self.interface.get_quodkey)

        # Action buttons
        if hasattr(self.dlg, 'load_to_canvas'):
            self.dlg.load_to_canvas.clicked.connect(lambda: self.interface.layerLoadQgis('manual'))
        if hasattr(self.dlg, 'save_csv'):
            self.dlg.save_csv.clicked.connect(self.interface.save_csv_file)
        if hasattr(self.dlg, 'Attachments'):
            self.dlg.Attachments.clicked.connect(self.interface.download_images)
        if hasattr(self.dlg, 'run_auto_pilot'):
            self.dlg.run_auto_pilot.clicked.connect(self.run_auto_pilot)

        # Close buttons
        if hasattr(self.dlg, 'closeWindow'):
            self.dlg.closeWindow.clicked.connect(self.dlg.reject)
        if hasattr(self.dlg, 'closeWindow_2'):
            self.dlg.closeWindow_2.clicked.connect(self.dlg.reject)
        if hasattr(self.dlg, 'closeWindow_3'):
            self.dlg.closeWindow_3.clicked.connect(self.dlg.reject)
        if hasattr(self.dlg, 'closeWindow_4'):
            self.dlg.closeWindow_4.clicked.connect(self.dlg.reject)

        if hasattr(self.dlg, 'reset_dialog'):
            self.dlg.reset_dialog.clicked.connect(lambda: self.interface.reset_dialog('reset'))

        # CRS selector
        if hasattr(self.dlg, 'crs'):
            self.dlg.crs.setEnabled(True)
            self.dlg.crs.setCrs(self.iface.mapCanvas().mapSettings().destinationCrs())
        if hasattr(self.dlg, 'crs_2'):
            self.dlg.crs_2.setEnabled(True)
            self.dlg.crs_2.setCrs(self.iface.mapCanvas().mapSettings().destinationCrs())

        # Initial button states
        if hasattr(self.dlg, 'attributeFilter'):
            self.dlg.attributeFilter.setEnabled(False)
        if hasattr(self.dlg, 'attributeFilter_2'):
            self.dlg.attributeFilter_2.setEnabled(False)
        if hasattr(self.dlg, 'valueFilter'):
            self.dlg.valueFilter.setEnabled(False)
        if hasattr(self.dlg, 'valueFilter_2'):
            self.dlg.valueFilter_2.setEnabled(False)
        if hasattr(self.dlg, 'filterExclude'):
            self.dlg.filterExclude.setEnabled(False)
        if hasattr(self.dlg, 'filterExclude_2'):
            self.dlg.filterExclude_2.setEnabled(False)
        if hasattr(self.dlg, 'Attachments'):
            self.dlg.Attachments.setEnabled(False)
        if hasattr(self.dlg, 'Attachments_2'):
            self.dlg.Attachments_2.setEnabled(False)
        if hasattr(self.dlg, 'save_csv'):
            self.dlg.save_csv.setEnabled(False)
        if hasattr(self.dlg, 'load_to_canvas'):
            self.dlg.load_to_canvas.setEnabled(False)

        # Load images
        if hasattr(self.dlg, 'WTT_label'):
            wtt = QPixmap(os.path.join(os.path.dirname(__file__), 'WTT.png'))
            self.dlg.WTT_label.setPixmap(wtt)
        pix = QPixmap(os.path.join(os.path.dirname(__file__), 'quodk.png'))
        auto_pix = QPixmap(os.path.join(os.path.dirname(__file__), 'quodk_auto.png'))
        auto_button_pix = QPixmap(os.path.join(os.path.dirname(__file__), 'auto-pilot.png'))
        if hasattr(self.dlg, 'QuODK_label'):
            self.dlg.QuODK_label.setPixmap(pix)
        if hasattr(self.dlg, 'QuODK_label_2'):
            self.dlg.QuODK_label_2.setPixmap(auto_pix)
        if hasattr(self.dlg, 'QuODK_label_go'):
            self.dlg.QuODK_label_go.setPixmap(auto_pix)
        if hasattr(self.dlg, 'run_auto_pilot'):
            self.dlg.run_auto_pilot.setIcon(QIcon(auto_button_pix))

        # Entity Management connections
        if hasattr(self.dlg, 'dataset_existing'):
            self.dlg.dataset_existing.activated.connect(self.interface.entity_list_properties)
        if hasattr(self.dlg, 'layer_to_Elist'):
            self.dlg.layer_to_Elist.activated.connect(self.interface.layer_to_entity_list)
        if hasattr(self.dlg, 'Elist_properties'):
            self.dlg.Elist_properties.view().setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        if hasattr(self.dlg, 'Elist_name'):
            self.dlg.Elist_name.editingFinished.connect(self.interface.check_list_exists)
            self.dlg.Elist_name.textEdited.connect(self.interface.reset_msg)
        if hasattr(self.dlg, 'Elist_label'):
            self.dlg.Elist_label.activated.connect(self.interface.update_properties_list)
        if hasattr(self.dlg, 'QGIS_KEY'):
            self.dlg.QGIS_KEY.activated.connect(self.interface.check_is_UUID)
        if hasattr(self.dlg, 'precheck_csv'):
            self.dlg.precheck_csv.clicked.connect(self.interface.precheck_csv)
        if hasattr(self.dlg, 'export_Elist_to_csv'):
            self.dlg.export_Elist_to_csv.clicked.connect(self.interface.entity_to_CSV)
        if hasattr(self.dlg, 'selected_features'):
            self.dlg.selected_features.toggled.connect(self.interface.use_selected)

        # Setup pyODK radio button group
        if hasattr(self.dlg, 'radio_new_code'):
            self.dlg.pyODK_code.resize(0, 0)

            self.interface.pyodk_radio = QButtonGroup()
            self.interface.pyodk_radio.addButton(self.dlg.radio_new_code, 1)
            if hasattr(self.dlg, 'radio_append_code'):
                self.interface.pyodk_radio.addButton(self.dlg.radio_append_code, 2)
            if hasattr(self.dlg, 'radio_update_code'):
                self.interface.pyodk_radio.addButton(self.dlg.radio_update_code, 3)
            if hasattr(self.dlg, 'radio_delete_code'):
                self.interface.pyodk_radio.addButton(self.dlg.radio_delete_code, 4)
            if hasattr(self.dlg, 'radio_merge_code'):
                self.interface.pyodk_radio.addButton(self.dlg.radio_merge_code, 5)
            self.interface.pyodk_radio.setExclusive(True)
            self.interface.pyodk_radio.buttonClicked.connect(self.interface.pyodk_buttons)

    def setup_ui_connections_auto_pilot(self):
        """Setup UI connections for Auto-Pilot dialog"""

        dlg = self.dlg_auto_pilot
        interface = self.interface_auto_pilot

        # Date controls - use 'auto' trigger for auto-pilot dialog
        if hasattr(dlg, 'DateStart'):
            dlg.DateStart.dateChanged.connect(interface.onAutoPilotDateChanged)
        if hasattr(dlg, 'DateEnd'):
            dlg.DateEnd.dateChanged.connect(interface.onAutoPilotDateChanged)
        if hasattr(dlg, 'sinceLastDownload'):
            dlg.sinceLastDownload.toggled.connect(interface.onAutoPilotDateChanged)
        if hasattr(dlg, 'btnSelectConfig'):
            dlg.btnSelectConfig.clicked.connect(interface.select_auto_pilot_file)
        if hasattr(dlg, 'unlock_quodkey'):
            dlg.quodkey_auto.setVisible(False)
            dlg.unlock_quodkey.setVisible(False)
            dlg.label_quodkey.setVisible(False)
            dlg.unlock_quodkey.clicked.connect(interface.unlock_quodkey)
        if hasattr(dlg, 'start_auto_pilot'):
            dlg.start_auto_pilot.setEnabled(False)
            dlg.start_auto_pilot.clicked.connect(interface.auto_pilot)
        if hasattr(dlg, 'Attachments_auto'):
            dlg.Attachments_auto.setEnabled(False)
            dlg.Attachments_auto.clicked.connect(interface.download_images)
        if hasattr(dlg, 'closeWindow'):
            dlg.closeWindow.clicked.connect(dlg.reject)
        if hasattr(dlg, 'attributeFilter'):
            dlg.attributeFilter.activated.connect(interface.filter_items_auto)
        if hasattr(dlg, 'valueFilter'):
            dlg.valueFilter.activated.connect(interface.filter_value_auto)
        if hasattr(dlg, 'clearFilter'):
            dlg.clearFilter.clicked.connect(interface.clearFilter_auto)
        if hasattr(dlg, 'filterExclude'):
            dlg.filterExclude.clicked.connect(interface.changeFilterState_auto)

        # Load logo image
        auto_pix = QPixmap(os.path.join(os.path.dirname(__file__), 'quodk_auto.png'))
        if hasattr(dlg, 'QuODK_label_go'):
            dlg.QuODK_label_go.setPixmap(auto_pix)
