# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuODK
                                 A QGIS plugin
 A link between ODK Central data and QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-30
        git sha              : $Format:%H$
        copyright            : (C) 2024-2026 by Walking-the-Talk
        email                : chris.york@walking-the-talk.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
QuODK Library - Core functionality for ODK Central API interactions and data processing
This module provides pure library functions with no UI dependencies.
Adapted with 'help' from Claude (but not very well) and Junie (a bit better)
"""

import json
import os
from pathlib import Path
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo
import pandas as pd
import requests
from requests.exceptions import Timeout, RequestException

# Request timeouts: (connect_timeout, read_timeout)
REQUEST_TIMEOUT = (5, 30)

from qgis.core import (QgsVectorLayer, QgsFeature, QgsField, QgsGeometry,
                       QgsCoordinateReferenceSystem, QgsCoordinateTransform,
                       QgsProject, QgsExpressionContextUtils, QgsWkbTypes,
                       QgsVectorLayerUtils, edit)
from qgis.PyQt.QtCore import QSettings, QMetaType, Qt
from math import isnan

# =============================================================================
# Utility Functions
# =============================================================================

def timeaware(base_time):
    """
    Convert datetime to timezone-aware format handling UTC/local time differences.
    Works across platforms including Windows without additional dependencies.

    Args:
        base_time: QDateTime or datetime object

    Returns:
        datetime: Timezone-adjusted datetime
    """
    try:
        utc_zone = ZoneInfo('UTC')
        local_zone = ZoneInfo('localtime')
        # Convert the UTC time to local time
        utc_time = base_time.replace(tzinfo=utc_zone)
        local_time = utc_time.astimezone(local_zone)
        time_diff = utc_time - local_time
    except Exception:  # Fallback for Windows/systems without ZoneInfo
        utc_time = datetime.now(timezone.utc)
        local_time = datetime.now().astimezone()
        time_diff = utc_time - local_time
    if isinstance(base_time,datetime):
        base_diff = base_time - time_diff
    else:
        base_diff = base_time.toPyDateTime() - time_diff
    return base_diff


def construct_geometry(df_layer, layerGeom, geomName, geomCol):
    """
    Convert ODK geometry coordinates to WKT format (POINTZM/LINESTRINGZM/POLYGONZM).

    Args:
        df_layer: pandas DataFrame with ODK data
        layerGeom: Geometry type (Point, LineString, Polygon, or NOGEOMETRY)
        geomName: Name of geometry field
        geomCol: Column name containing coordinates

    Returns:
        pandas DataFrame with 'geom_from_ODK' column populated with WKT strings
    """
    nogeom = 0
    #print('df_layer:',df_layer)
    for i, iData in df_layer.iterrows():
        iValues = df_layer.loc[i, geomCol]

        if iValues is None:
            # No geometry data
            WKT = "NOGEOMETRY"
            nogeom += 1
        elif type(iValues) is list:
            # Convert to table only
            if str(layerGeom) == "NOGEOMETRY":
                WKT = "NOGEOMETRY"
                nogeom += 1

            # Convert to Point WKT
            elif str(layerGeom) == "Point":
                m = str(df_layer.loc[i, str(geomName+'-accuracy')])
                XYZ = " ".join(map(str, iValues))
                WKT = ("POINTZM (" + XYZ + " " + m +")")

            # Convert to LineString WKT
            elif str(layerGeom) == "LineString":
                c = ""
                for a in iValues:
                    b = ("".join(str(a))[1:][:-1]).replace(",", "")
                    if len(a) == 2:
                        c = c + ", " + b + " 0 0"
                    elif len(a) == 3:
                        c = c + ", " + b + " 0"
                    else:
                        c = c + ", " + b
                XYZ = c[1:]
                WKT = ("LINESTRINGZM (" + XYZ +")")

            # Convert to Polygon WKT
            elif str(layerGeom) == "Polygon":
                c = ""
                for a in iValues[0]:
                    b = ("".join(str(a))[1:][:-1]).replace(",", "")
                    if len(a) == 2:
                        c = c + ", " + b + " 0 0"
                    elif len(a) == 3:
                        c = c + ", " + b + " 0"
                    else:
                        c = c + ", " + b
                XYZ = c[1:]
                WKT = ("POLYGONZM ((" + XYZ + "))")
            else:
                WKT = "NOGEOMETRY"
                nogeom += 1
        else:
            WKT = "NOGEOMETRY"
            nogeom += 1

        # Add geometry to dataframe
        df_layer.loc[i, 'geom_from_ODK'] = str(WKT)

    return df_layer, nogeom


def construct_entity_geometry(df_layer, geomCol):
    """
    Convert entity geometry (stored as semicolon-separated coordinates) to WKT format.
    Generates separate layers for each geometry type if entities have mixed geometries.

    Args:
        df_layer: pandas DataFrame with entity data
        geomCol: Column name containing geometry string

    Returns:
        tuple: (DataFrame with 'geom_from_ODK' column, string of geometry types found)
    """
    geomTypes = ''

    for i, iData in df_layer.iterrows():
        iValues = df_layer.loc[i, geomCol]

        if iValues:
            # Parse semicolon-separated coordinates: "lat lon alt acc; lat lon alt acc; ..."
            vertices = iValues.split(";")
            c = ""

            # Determine geometry type based on vertex count and closure
            if len(vertices) == 1:
                geomType = "POINT"
            elif vertices[0] == vertices[-1].lstrip(' '):
                geomType = "POLYGON"
            else:
                geomType = "LINESTRING"

            # Convert each vertex from "lat lon alt acc" to "lon lat alt acc" (x y z m)
            for a in vertices:
                a = a.lstrip(' ')  # Remove leading spaces
                coords = a.split(" ")
                # Swap lat/lon to lon/lat for WKT format
                b = coords[1] + " " + coords[0] + " " + coords[2] + " " + coords[3]
                c = c + ", " + b

            XYZ = c[1:]
            WKT = (geomType + "ZM ((" + XYZ +"))")
            df_layer.loc[i, 'geom_from_ODK'] = str(WKT)
        else:
            geomType = "NOGEOMETRY"
            df_layer.loc[i, 'geom_from_ODK'] = 'NOGEOMETRY'

        # Track unique geometry types found
        if geomType not in geomTypes:
            geomTypes += str(geomType + ' ')

    return df_layer, geomTypes.strip()


def check_column_underscore(df_table, underscore_columns):
    """
    Check for underscore-containing column names that may have been transformed by OData.
    OData substitutes dash (-) for underscore (_) which can cause issues.

    Args:
        df_table: pandas DataFrame
        underscore_columns: List of expected underscore column names

    Returns:
        list: Column names containing underscores (excluding system columns)
    """
    headings = list(df_table)
    underscored = []

    for heading in headings:
        # Check for single underscore (not double underscore system columns, not base_version)
        if '_' in heading and '__' not in heading and 'base_version' not in heading:
            underscored.append(heading)

    return underscored

def load_layer_to_canvas(df_layer, LayerName, keyLevel,geomType, projection='EPSG:4326'):
    nogeom = 0
    calc = geomType.find('_calculated_geometry_')
    if keyLevel == "ENTITY_KEY" or calc != -1:
        # Entity geometry
        geomName = str(geomType)
        geomCol = str(geomType)
        # Construct entity geometry (or combined geometry)
        df_canvas_layer, entityGeom = construct_entity_geometry(df_layer, geomCol)
        layerGeom = entityGeom
    else:
        if "NOGEOMETRY" in geomType:
            layerGeom = "NOGEOMETRY"
            geomName = ""
            geomCol = "geom_from_ODK"
        else:
            # Submission geometry
            layerGeom = str(str(geomType).split("--->")[-1:][0])
            geomName = str(str(geomType).split("--->")[0])
            geomCol = f"{geomName}-coordinates"
        df_canvas_layer, nogeom = construct_geometry(df_layer, layerGeom, geomName, geomCol)
    # Create QGIS layer for each geometry type
    for geoms in layerGeom.split():

        df_splitlayer = df_canvas_layer[df_canvas_layer['geom_from_ODK'].str.contains(geoms.upper())]
        df_splitlayer.index = range(len(df_splitlayer.index))
        if geoms == "NOGEOMETRY":
            LayerType = f"POINTZM?crs={projection}"
            layer_name = f"{LayerName}_TABLE"
        else:

            LayerType = f"{geoms.upper()}ZM?crs={projection}"
            layer_name = f"{LayerName}_{geoms.upper()}"
        # print(self.projection, layer_name, LayerType)
        # Create memory layer
        temp = QgsVectorLayer(LayerType, layer_name, "memory")
        temp_data = temp.dataProvider()
        temp.startEditing()

        # Create fields
        headers = list(df_splitlayer)
        ignoregeom = ["geom_from_ODK", "entity_geom", "geometry", "calculated_geometry"]

        for header in headers:
            if header not in ignoregeom:
                datatype = df_splitlayer[header].dtype

                if datatype == 'object':
                    temp_data.addAttributes([QgsField(header, QMetaType.Type.QString)])
                elif datatype == 'int64':
                    temp_data.addAttributes([QgsField(header, QMetaType.Type.Int)])
                elif datatype == 'float64':
                    temp_data.addAttributes([QgsField(header, QMetaType.Type.Double, 'double', 20, 3)])
                else:
                    temp_data.addAttributes([QgsField(header, QMetaType.Type.QString)])

        temp.updateFields()

        # Add features with geometry
        for i, row in df_splitlayer.iterrows():
            if str(geoms) == "NOGEOMETRY":
                geom = ""
            else:
                geom = df_splitlayer.loc[i, 'geom_from_ODK']

            qFeat = QgsFeature()
            base_geom = QgsGeometry.fromWkt(geom)

            # Transform to target CRS
            sourceCrs = QgsCoordinateReferenceSystem("EPSG:4326")
            destCrs = QgsCoordinateReferenceSystem(projection)
            tr = QgsCoordinateTransform(sourceCrs, destCrs, QgsProject.instance())

            if str(geoms) != "NOGEOMETRY":
                base_geom.transform(tr)

            qFeat.setGeometry(base_geom)
            temp_data.addFeatures([qFeat])
            temp.commitChanges()
            temp.updateFields()
            temp.updateExtents()

        # Populate attribute table
        features = temp.getFeatures()
        count = 0

        for feature in features:
            for header in headers:
                if header not in ignoregeom:
                    with edit(temp):
                        datatype = df_splitlayer[header].dtype
                        attributeValue = df_splitlayer.loc[count, header]

                        if attributeValue is None:
                            pass
                        elif datatype == 'object':
                            feature[header] = str(attributeValue)
                        else:
                            if isnan(attributeValue):
                                feature[header] = None
                            else:
                                feature[header] = float(attributeValue)

                        temp.updateFeature(feature)
            count += 1

        temp.commitChanges()
        QgsProject.instance().addMapLayer(temp)
        return nogeom, count

# =============================================================================
# ODK Central Session Token Management
# =============================================================================

class SessionToken:
    """
    Manages ODK Central session authentication tokens.
    Handles login and token caching to avoid repeated authentication.
    """

    def __init__(self, odk_url, username, password):
        """
        Initialize session token manager.

        Args:
            odk_url: ODK Central server URL
            username: Email address for authentication
            password: Password for authentication
        """
        self.odk_url = odk_url.rstrip('/')  # Remove trailing slash
        self.username = username
        self.password = password
        self.token = ''

    def get_token(self):
        """
        Get session token, logging in if necessary.

        Returns:
            str: Session token on success

        Raises:
            ConnectionError: If unable to connect to server
            ValueError: If credentials are invalid
        """
        # Return cached token if valid
        if len(self.token) > 5:
            return self.token

        # Authenticate with ODK Central
        session_url = f"{self.odk_url}/v1/sessions"

        try:
            response = requests.post(
                session_url,
                data=json.dumps({
                    "email": self.username,
                    "password": self.password
                }),
                headers={"Content-Type": "application/json"},
                timeout=REQUEST_TIMEOUT
            )

            if response.status_code == 200:
                self.token = response.json()["token"]
                return self.token
            else:
                print (f"Authentication failed: {response.status_code}")
                raise ValueError(f"Authentication failed: {response.status_code}")

        except Timeout:
            print(f"Request timed out connecting to {self.odk_url}")
            raise ConnectionError(f"Request timed out connecting to {self.odk_url}")

        except RequestException as e:
            print(f"Request failed: {str(e)}")
            raise ConnectionError(f"Request failed: {str(e)}")


# =============================================================================
# ODK Central Data Access
# =============================================================================

class CentralDataGrab:
    """
    Main class for retrieving data from ODK Central via API.
    Handles projects, forms, submissions, entities, and repeat groups.
    """

    def __init__(self, session_token, odk_url):
        """
        Initialize data accessor.

        Args:
            session_token: Valid ODK Central session token
            odk_url: ODK Central server URL
        """
        self.session_token = session_token
        self.odk_url = odk_url.rstrip('/')
        self.projects_url = f"{self.odk_url}/v1/projects/"

    def _make_request(self, method, url, **kwargs):
        """
        Internal method to make HTTP requests with standardized timeout and error handling.
        """
        if 'timeout' not in kwargs:
            kwargs['timeout'] = REQUEST_TIMEOUT

        try:
            return requests.request(method, url, **kwargs)
        except Timeout:
            print(f"Request timed out connecting to {url}")
            raise ConnectionError(f"Request timed out connecting to {url}")
        except RequestException as e:
            print(f"Request failed for {url}: {str(e)}")
            raise ConnectionError(f"Request failed: {str(e)}")

    def list_projects(self):
        """
        List all projects accessible with current credentials.

        Returns:
            list: List of project dictionaries with 'id' and 'name' keys

        Raises:
            requests.HTTPError: If request fails
        """
        response = self._make_request(
            'GET',
            self.projects_url,
            headers={"Authorization": f"Bearer {self.session_token}"}
        )
        response.raise_for_status()
        return response.json()

    def list_forms(self, project_id):
        """
        List all forms in a project.

        Args:
            project_id: Project ID number

        Returns:
            list: List of form dictionaries with 'xmlFormId' and 'name' keys
        """
        form_url = f"{self.projects_url}{project_id}/forms/"
        response = self._make_request(
            'GET',
            form_url,
            headers={"Authorization": f"Bearer {self.session_token}"}
        )
        response.raise_for_status()
        return response.json()

    def list_entity_lists(self, project_id):
        """
        List all entity lists (datasets) in a project.

        Args:
            project_id: Project ID number

        Returns:
            list: List of entity list names
        """
        dataset_url = f"{self.projects_url}{project_id}/datasets/"
        response = self._make_request(
            'GET',
            dataset_url,
            headers={"Authorization": f"Bearer {self.session_token}"}
        )

        if response.status_code == 200:
            return [ds["name"] for ds in response.json()]
        else:
            return []

    def list_repeat_groups(self, project_id, xml_form_id):
        """
        List all repeat groups within a form.

        Args:
            project_id: Project ID number
            xml_form_id: Form XML ID

        Returns:
            tuple: (repeat_data list, related_entity_list name or None)
        """
        form_url = f"{self.projects_url}{project_id}/forms/"
        svc_url = f"{form_url}{xml_form_id}.svc"
        dataset_diff_url = f"{form_url}{xml_form_id}/dataset-diff"

        # Get repeat group structure
        svc_response = self._make_request(
            'GET',
            svc_url,
            headers={"Authorization": f"Bearer {self.session_token}"}
        )

        repeat_data = []
        if svc_response.status_code == 200:
            repeat_data = svc_response.json()['value']
        else:
            repeat_data = None

        # Check for associated entity list
        related_entity_list = None
        dataset_diff_response = self._make_request(
            'GET',
            dataset_diff_url,
            headers={"Authorization": f"Bearer {self.session_token}"}
        )

        if dataset_diff_response.status_code == 200:
            try:
                dataset_diff = dataset_diff_response.json()[0]
                if dataset_diff:
                    related_entity_list = dataset_diff['name']
            except (IndexError, KeyError):
                pass

        return repeat_data, related_entity_list

    def get_submissions(self, project_id, xml_form_id, repeat_group=None, date_start=None, date_end=None,
                        top_n=None, selected_fields=None):
        """
        Get form submissions, optionally filtered by date range and repeat group.

        Args:
            project_id: Project ID number
            xml_form_id: Form XML ID
            date_start: Start date string in ODK format (optional)
            date_end: End date string in ODK format (optional)
            repeat_group: Repeat group name (optional, None for main form)
            top_n: Limit to top N results (optional)

        Returns:
            tuple: DataFrame of submissions, list of geometry options, server response code, response message (in case of error)
        """
        form_url = f"{self.projects_url}{project_id}/forms/"
        # Build filter URL
        if repeat_group != "Main": #i.e. this is a repeat group
            base_url = f"{form_url}{xml_form_id}.svc/Submissions.{repeat_group}"
            key_level = "PARENT_KEY"

            if date_start and date_end:
                filter_url = (f"{base_url}?$filter=$root/Submissions/"
                            f"__system/submissionDate ge {date_start} and "
                            f"$root/Submissions/__system/submissionDate le {date_end}")
            else:
                filter_url = base_url
        else: #i.e. this is the main form
            base_url = f"{form_url}{xml_form_id}.svc/Submissions"
            key_level = "KEY"

            if top_n: #only used when using config screen
                filter_url = f"{base_url}?$top={top_n}"
            elif selected_fields:
                filter_url = (f"{base_url}?$select={selected_fields}")
            elif date_start and date_end:
                filter_url = (f"{base_url}?$filter="
                            f"__system/submissionDate ge {date_start} and "
                            f"__system/submissionDate le {date_end}")
            else: #this will download all submissions for this form
                filter_url = base_url

        # Fetch data
        df_odk, geom_options, response_code, server_response = self._get_odata_response(filter_url, key_level, repeat_group or "Main")
        return df_odk, geom_options, response_code, server_response

    def get_entities(self, project_id, entity_list_name, date_start=None, date_end=None,
                    status="New", selected_fields=None):
        """
        Get entities from an entity list, optionally filtered by date and status.

        Args:
            project_id: Project ID number
            entity_list_name: Name of entity list
            date_start: Start date string in ODK format (optional)
            date_end: End date string in ODK format (optional)
            status: "New" or "Updated" (default: "New")

        Returns:
            tuple: (DataFrame of entities, list of geometry options)
        """
        dataset_url = f"{self.projects_url}{project_id}/datasets/"

        # Build filter based on status
        if status == "New" and (date_start and date_end):
            filter_url = (f"{dataset_url}{entity_list_name}.svc/Entities?$filter="
                        f"__system/createdAt ge {date_start} and "
                        f"__system/createdAt le {date_end}")
        elif status == "Updated" and (date_start and date_end):
            filter_url = (f"{dataset_url}{entity_list_name}.svc/Entities?$filter="
                        f"__system/updatedAt ge {date_start} and "
                        f"__system/updatedAt le {date_end}")
        elif status == 'filter':
            print('filter')
            filter_url = f"{dataset_url}{entity_list_name}.svc/Entities?$select={selected_fields}"
        else:
            filter_url = f"{dataset_url}{entity_list_name}.svc/Entities?$top={5}"
        # Fetch data
        print(filter_url)
        df_odk, geom_options, response_code, server_response = self._get_odata_response(filter_url, "ENTITY_KEY", entity_list_name)

        return df_odk, geom_options, response_code, server_response

    def get_odata_filter(self, project_id, xml_form_id, selected_fields=None):
        """
        Internal method to fetch and process OData API responses. Olny accessible once credentials are confirmed valid

        Args:
            project_id: Project ID number
            xml_form_id: Form ID number
            selected_fields: Comma-separated list of fields to include in the filter request

        Returns:
            tuple: (DataFrame, list of geometry field options)
        """
        if '.' in selected_fields:
            selected_fields = selected_fields.replace('.', '/')
        form_url = f"{self.projects_url}{project_id}/forms/"
        base_url = f"{form_url}{xml_form_id}.svc/Submissions"
        filter_url = (f"{base_url}?$select={selected_fields}")
        response = self._make_request(
            'GET',
            filter_url,
            headers={"Authorization": f"Bearer {self.session_token}"}
        )
        response.raise_for_status()

        odk_json = response.json()['value']
        df_all_values = pd.json_normalize(odk_json)

        return df_all_values

    def _get_odata_response(self, filter_url, key_level, repeat_group):
        """
        Internal method to fetch and process OData API responses.

        Args:
            filter_url: Complete API URL with filters
            key_level: Type of key ("KEY", "PARENT_KEY", or "ENTITY_KEY")
            repeat_group: Name of repeat group or entity list

        Returns:
            tuple: (DataFrame, list of geometry field options)
        """
        geom_options = []
        response = self._make_request(
            'GET',
            filter_url,
            headers={"Authorization": f"Bearer {self.session_token}"}
        )

        server_response = {'message': response.json()['message'] if 'message' in response.json() else None,'code': response.json()['code'] if 'code' in response.json() else None}

        print(server_response)
        if response.status_code != 200:
            return None, geom_options,response.status_code,server_response
        else:
            odk_json = response.json()['value']
            # Create DataFrame from normalized JSON
            df_odk = pd.json_normalize(odk_json)
            if df_odk.shape[0] == 0:
                return df_odk, geom_options,response.status_code,server_response
            df_odk = df_odk.assign(geom_from_ODK=None)  # Column for WKT geometry

            geom_keys = ["Point", "LineString", "Polygon"]
            headers = list(df_odk)
            col_number = 0

            # Process column names and identify geometry fields
            for header in headers:
                geom_name = ''
                if header.find('.') > -1:
                    # Clean up nested field names
                    header = header.replace('.properties.', '-')
                    header = header.replace('.coordinates', '-coordinates')
                    df_odk.rename(columns={df_odk.columns[col_number]: header}, inplace=True)

                    # Find first non-null index to check data type
                    notnullindex = df_odk[header].first_valid_index()
                    if notnullindex is None:
                        notnullindex = 0

                    # Check if this is a geometry type field
                    if df_odk.loc[notnullindex, header] in geom_keys:
                        geom_type = df_odk.loc[notnullindex, header]
                        geom_name = str(header.rsplit('.', 1)[0])
                        geom_item = f"{geom_name}--->{geom_type}"
                        geom_options.append({"repeatGroup": str(repeat_group), "geomOptions" :geom_item})

                # Rename ID columns based on key level
                if key_level in ('KEY', 'PARENT_KEY'):
                    header = header.replace('__id', 'KEY')
                    if 'geometry' in header and not geom_name:
                        header = header.replace('geometry', '_calculated_geometry_')
                        geom_options.append({"repeatGroup": str(repeat_group), "geomOptions" : header})
                elif key_level == 'ENTITY_KEY':
                    header = header.replace('__id', 'ENTITY_KEY')
                    header = header.replace('geometry', 'entity_geom')
                    if header == 'entity_geom':
                        geom_options.append({"repeatGroup": "ENTITY", "geomOptions" : "entity_geom"})

                header = header.replace('__Submissions-id', 'PARENT_KEY')

                df_odk.rename(columns={df_odk.columns[col_number]: header}, inplace=True)
                col_number += 1

            if not geom_options:
                geom_options.append({"repeatGroup": str(repeat_group), "geomOptions" : "NOGEOMETRY"})
            return df_odk, geom_options,response.status_code,server_response


    def download_attachments(self, project_id, xml_form_id, submission_keys,
                            destination_folder, total, username, password, overwrite, progress_callback=None):
        """
        Download attachments for specified submissions.

        Args:
            project_id: Project ID number
            xml_form_id: Form XML ID
            submission_keys: List of submission KEY values
            destination_folder: Path to save attachments
            total: Total number of submissions expected (comes from self.AttachmentsTotal)
            username: ODK username for auth
            password: ODK password for auth
            overwrite: Overwrite existing files (False by default)
            progress_callback: Optional function(current, total) for progress updates

        Returns:
            int: Number of attachments downloaded
        """
        form_url = f"{self.projects_url}{project_id}/forms/"
        count = 0
        skipped = 0
        missingnum = 0
        missinglist = ''

        for key in submission_keys:
            attach_url = f"{form_url}{xml_form_id}/submissions/{key}/attachments"
            response = self._make_request(
                'GET',
                attach_url,
                headers={"Authorization": f"Bearer {self.session_token}"}
            )

            if response.status_code == 200:
                attachments = response.json()
                for attachment in attachments:
                    filename = attachment['name']
                    source_url = f"{attach_url}/{filename}"
                    if filename == 'audit.csv':
                        keyid = key.replace('uuid:', 'key--')
                        audit_file = f"audit-{keyid}.csv"
                        destination = os.path.join(destination_folder, audit_file)
                    else:
                        destination = os.path.join(destination_folder, filename)
                    if os.path.exists(destination) and overwrite is False:
                        skipped += 1
                        if progress_callback:
                            progress_callback((count+skipped), total)
                        pass
                    else:
                        # Download file
                        stream_response = self._make_request(
                            'GET',
                            source_url,
                            auth=(username, password),
                            stream=True,
                            allow_redirects=True
                        )
                        if stream_response.status_code == 200:
                            with open(destination, 'wb') as f:
                                f.write(stream_response.content)
                            count += 1
                        else:
                            missingnum += 1
                            missinglist += f"{filename} ; "
                        if progress_callback:
                            progress_callback((count+skipped), total)

        missing = str(missingnum) + ' failed: ' + missinglist
        return count, missing, skipped
