# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuODK
                                 A QGIS plugin
 A link between ODK Central data and QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-30
        git sha              : $Format:%H$
        copyright            : (C) 2024-2026 by Walking-the-Talk
        email                : chris.york@walking-the-talk.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from cryptography.fernet import Fernet as F
from qgis.PyQt.QtCore import QSettings
from qgis.core import QgsExpressionContextUtils, QgsProject


class manage_credentials:
    def __init__(self):
        """Initialize credential manager: encrypts / decrypts the ODK Central password using Fernet Key

        """
        #NOTE: self.whisk is used to unlock the (shared) QuODKey generated in the UI to allow initial use of an auto-pilot config file -
        # it used only once for each auto-pilot file (if it is supplied locked) and a new (or existing) QuODKey is used for all subsequent operations
        #once unlocked the original (shared) QuODKey is useless and can be deleted
        self.whisk = b'6dWSvWrrjwyGzCECetswdOUuRAFr7XrLmWVvIH4Qwjk='
        self.QuODKey = self.get_QuODKey()

    def get_QuODKey(self):
        """Get the local key from QGIS global variable."""
        try:
            defaults = QSettings()
            local_key = defaults.value('QuODK/quodkey', '')
            if not local_key:
                try:
                    key = F.generate_key()
                    local_key = key.decode() if isinstance(key, bytes) else key
                    defaults.setValue('QuODK/quodkey', local_key)
                except Exception as e:
                    print(f"Error creating personal key: {e}")
                    return None
            return local_key.encode() if isinstance(local_key, str) else local_key
        except Exception as e:
            print(f"Error creating personal key: {e}")
            return None

    def unscramble(self, odkpass, odkuser, trigger):
        """Decrypt the file using appropriate key.
        """
        feedback = None
        try:
            if trigger == 'config':
                unscrambled = F(self.whisk).decrypt(odkpass.encode())
                unscrambled_user = F(self.whisk).decrypt(odkuser.encode())
            else:
                unscrambled = F(self.QuODKey).decrypt(odkpass.encode())
                unscrambled_user = F(self.QuODKey).decrypt(odkuser.encode())
            if unscrambled:
                feedback = 'Unlocked'
                return unscrambled.decode(), unscrambled_user.decode(), feedback
            else:
                feedback = 'No credentials found'
                return None, None, feedback

        except Exception as e:
            print(f"Error decrypting with QuODKey: {e}")
            feedback = f"The key provided does not fit this lock {e}"
            if trigger != 'manual':
                feedback += '\n\nIt is possible that you are using an auto-pilot config file that was generated / unlocked on a different computer.'
                return None, None, feedback

    def scrambler(self, odkpass, odkuser, trigger):
        if trigger == 'config':
            scrambled = F(self.whisk).encrypt(odkpass.encode())
            scrambled_user = F(self.whisk).encrypt(odkuser.encode())
        else:
            if not(self.QuODKey):
                self.get_QuODKey()
            scrambled = F(self.QuODKey).encrypt(odkpass.encode())
            scrambled_user = F(self.QuODKey).encrypt(odkuser.encode())
        return scrambled.decode(), scrambled_user.decode()

    def generate_encryption_key(self, odkpass,odkuser):
        """
        Create quodkey encryption key and scramble user and pass for transit.
        """
        locked_pass = None
        locked_user = None
        quodkey = F.generate_key()
        key_return = quodkey.decode() if isinstance(quodkey, bytes) else quodkey
        try:
            locked_pass = F(self.whisk).encrypt(F(quodkey).encrypt(odkpass.encode())).decode()
            locked_user = F(self.whisk).encrypt(F(quodkey).encrypt(odkuser.encode())).decode()

        except Exception as e:
            print(f"Error encrypting with combo-key: {e}")

        if locked_pass and locked_user:
            return key_return, locked_pass, locked_user
        else:
            return key_return, None, None
        # Display in the QuODKey_generated text field


    def unlock_permissions(self,odkpass, odkuser, quodkey):
        feedback = None
        try:
            bytepass = odkpass.encode() if isinstance(odkpass, str) else odkpass
            byteuser = odkuser.encode() if isinstance(odkuser, str) else odkuser
            key = (quodkey.encode()) if isinstance(quodkey, str) else quodkey

            unlocked = F(key).decrypt(F(self.whisk).decrypt(bytepass)).decode()
            unlocked_user = F(key).decrypt(F(self.whisk).decrypt(byteuser)).decode()
            #re-encrypt with QuODKey (create new key if required)
            if unlocked and unlocked_user:
                unlocked_scrambled = self.scrambler(unlocked,unlocked_user, 'auto')
                feedback = 'Unlocked'
                return unlocked_scrambled[0], unlocked_scrambled[1], feedback
            else:
                feedback = 'No credentials found'
                return None, None, feedback


        except Exception as e:
            print(f"Error decrypting with provided QuODKey: {e}")
            feedback = f"The key provided does not fit this lock: {e}"
            return None, None, feedback