# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuODK
                                 A QGIS plugin
 A link between ODK Central data and QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-30
        git sha              : $Format:%H$
        copyright            : (C) 2024-2026 by Walking-the-Talk
        email                : chris.york@walking-the-talk.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from cryptography.fernet import Fernet as F
from qgis.PyQt.QtCore import QSettings
from qgis.core import QgsExpressionContextUtils, QgsProject


class manage_credentials:
    def __init__(self):
        """Initialize credential manager: encrypts / decrypts the ODK Central password using Fernet Key

        """
        #NOTE: self.whisk is used to unlock the (shared) QuODKey generated in the UI to allow initial use of an auto-pilot config file -
        # it used only once for each auto-pilot file (if it is supplied locked) and a new (or existing) QuODKey is used for all subsequent operations
        #once unlocked the original (shared) QuODKey is useless and can be deleted
        self.QuODKey = self.get_QuODKey()

    def get_QuODKey(self):
        """Get the local key from QGIS global variable."""
        try:
            defaults = QSettings()
            local_key = defaults.value('QuODK/quodkey', '')
            if not local_key:
                try:
                    key = F.generate_key()
                    local_key = key.decode() if isinstance(key, bytes) else key
                    defaults.setValue('QuODK/quodkey', local_key)
                except Exception as e:
                    print(f"Error creating personal key: {e}")
                    return None
            return local_key.encode() if isinstance(local_key, str) else local_key
        except Exception as e:
            print(f"Error creating personal key: {e}")
            return None

    def unscramble(self, odkpass, odkuser, trigger, quodkey=None):
        """Decrypt the file using the appropriate key.
        """
        feedback = None
        try:
            if trigger == 'config':
                if quodkey:
                    unscrambled = F(quodkey).decrypt(odkpass.encode())
                    unscrambled_user = F(quodkey).decrypt(odkuser.encode())
                else:
                    feedback = 'No QuODKey found'
                    return None, None, feedback
            else:
                unscrambled = F(self.QuODKey).decrypt(odkpass.encode())
                unscrambled_user = F(self.QuODKey).decrypt(odkuser.encode())
            if unscrambled:
                feedback = 'Unlocked'
                return unscrambled.decode(), unscrambled_user.decode(), feedback
            else:
                feedback = 'No credentials found'
                return None, None, feedback

        except Exception as e:
            print(f"Error decrypting with QuODKey: {e}")
            feedback = f"The key provided does not fit this lock {e}"
            if trigger != 'manual':
                feedback += '\n\nIt is possible that you are using an auto-pilot config file that was generated / unlocked on a different computer.'
                return None, None, feedback

    def scrambler(self, odkpass, odkuser, trigger, quodkey=None):
        if trigger == 'config':
            if not(quodkey):
                return None, None, 'No QuODKey provided'
            key = (quodkey.encode()) if isinstance(quodkey, str) else quodkey
            scrambled = F(key).encrypt(odkpass.encode())
            scrambled_user = F(key).encrypt(odkuser.encode())
        else:
            if not(self.QuODKey):
                self.get_QuODKey()
            scrambled = F(self.QuODKey).encrypt(odkpass.encode())
            scrambled_user = F(self.QuODKey).encrypt(odkuser.encode())
        return scrambled.decode(), scrambled_user.decode(), 'Locked'

    def scramble_filters(self, filters, trigger, quodkey=None):
        """Encrypt filter values."""
        if trigger == 'config':
            if not quodkey:
                return filters
            key = (quodkey.encode()) if isinstance(quodkey, str) else quodkey
        else:
            if not self.QuODKey:
                self.get_QuODKey()
            key = self.QuODKey

        if not key:
            return filters

        scrambled = {}
        fernet = F(key)
        for k, v in filters.items():
            if v:
                scrambled[k] = fernet.encrypt(str(v).encode()).decode()
            else:
                scrambled[k] = fernet.encrypt("__QuODK__".encode()).decode()
        return scrambled

    def unscramble_filters(self, filters, trigger, quodkey=None):
        """Decrypt filter values."""
        if trigger == 'config':
            if not quodkey:
                return filters
            key = (quodkey.encode()) if isinstance(quodkey, str) else quodkey
        else:
            if not self.QuODKey:
                self.get_QuODKey()
            key = self.QuODKey

        if not key:
            return filters

        unscrambled = {}
        fernet = F(key)
        for k, v in filters.items():
            if v:
                try:
                    unscrambled[k] = fernet.decrypt(str(v).encode()).decode()
                    if unscrambled[k] == "__QuODK__":
                        unscrambled[k] = None
                except Exception:
                    unscrambled[k] = v
            else:
                unscrambled[k] = v
        return unscrambled

    def generate_encryption_key(self, odkpass,odkuser):
        """
        Create quodkey encryption key and scramble user and pass for transit.
        """
        quodkey = F.generate_key()
        key_return = quodkey.decode() if isinstance(quodkey, bytes) else quodkey
        locked = self.scrambler(odkpass, odkuser, 'config', key_return)
        if locked:
            return key_return, locked[0], locked[1]
        else:
            return key_return, None, None
        # Display in the QuODKey_generated text field


    def unlock_permissions(self,odkpass, odkuser, quodkey, filters=None):
        feedback = None
        try:
            intermediate = self.unscramble(odkpass, odkuser, 'config', quodkey)
            unscrambled_filters = self.unscramble_filters(filters, 'config', quodkey) if filters else {}
            feedback = f"{intermediate[2]}\n"
            #re-encrypt with QuODKey (create new key if required)
            if intermediate[2] == 'Unlocked':
                unlocked_scrambled = self.scrambler(intermediate[0],intermediate[1], 'auto')
                re_encrypted_filters = self.scramble_filters(unscrambled_filters, 'auto')
                feedback = 'Unlocked'
                return unlocked_scrambled[0], unlocked_scrambled[1], feedback, re_encrypted_filters
            else:
                feedback = 'No credentials found'
                return None, None, feedback, {}
        except Exception as e:
            print(f"{feedback} Error decrypting with provided QuODKey: {e}")
            feedback += f"The key provided does not fit this lock: {e}"
            return None, None, feedback, {}